"""Portable final-audio handoff, without third-party timeline promises."""
import csv
import html
import json
import re
import shutil
import tempfile
import zipfile
from pathlib import Path

import soundfile as sf


def _vtt_time(sample, rate):
    ms = round(sample * 1000 / rate)
    return f'{ms//3600000:02}:{ms//60000%60:02}:{ms//1000%60:02}.{ms%1000:03}'


def write_delivery(output, entries, rendered, rate, total_samples):
    """Use the exact PCM arrays already rendered for full.wav, not raw sources."""
    output = Path(output)
    with tempfile.TemporaryDirectory(prefix='.delivery-', dir=output) as temp:
        staging = Path(temp) / 'delivery'
        audio = staging / 'audio'
        audio.mkdir(parents=True)
        rows, cues = [], ['WEBVTT\n']
        for index, (entry, pcm) in enumerate(zip(entries, rendered, strict=True), 1):
            # Ordinals prevent collisions; metadata retains the original role name.
            role = re.sub(r'[^\w.-]', '_', entry['speaker'], flags=re.UNICODE).strip('._')[:40] or 'speaker'
            filename = f'audio/{index:04d}_{role}.wav'
            sf.write(staging / filename, pcm, rate, subtype='PCM_16')
            start, end = entry['file_start_sample'], entry['file_end_sample']
            rows.append({'index':index, 'speaker':entry['speaker'], 'start':start/rate,
                'end':end/rate, 'duration':len(pcm)/rate, 'file':filename, 'text':entry['text'],
                'id':entry['id'], 'start_sample':start, 'end_sample':end, 'samples':len(pcm),
                'sample_rate':rate, 'speech_start_sample':entry['speech_start_sample'],
                'speech_end_sample':entry['speech_end_sample'], 'synthetic_audio':True})
            cues.append(f"{index}\n{_vtt_time(entry['speech_start_sample'],rate)} --> {_vtt_time(entry['speech_end_sample'],rate)}\n{html.escape(entry['text'],quote=False)}\n")
        timeline = {'schema_version':1, 'synthetic_audio':True, 'sample_rate':rate,
            'total_samples':total_samples, 'seconds_fields':['start','end','duration'],
            'sample_fields_are_authoritative':True, 'end_sample_is_exclusive':True,
            'audio_processing':'final_rendered_pcm; speed and clip edits already applied',
            'reconstruction_tolerance_samples':0, 'segments':rows}
        (staging/'timeline.json').write_text(json.dumps(timeline,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
        with (staging/'timeline.csv').open('w',encoding='utf-8-sig',newline='') as stream:
            writer = csv.DictWriter(stream,fieldnames=list(rows[0]),quoting=csv.QUOTE_ALL)
            writer.writeheader();writer.writerows(rows)
        shutil.copyfile(output/'subtitles.srt',staging/'subtitles.srt')
        (staging/'subtitles.vtt').write_text('\n'.join(cues),encoding='utf-8')
        (staging/'README.txt').write_text('''VoxStage · Portable audio delivery / 可移植音频交付包

All audio in audio/ is AI-generated speech. Speed changes and clip edits are
already applied. These WAVs are final sentence audio, not raw model outputs.
所有 WAV 均为合成语音，已应用当前变速与剪辑。

Keep this folder together. Every file path in timeline.csv and timeline.json
is relative to this folder. You may rename or move the folder as a whole.
请整体移动或改名；时间轴中的文件路径相对于本文件所在目录。

Each row names the speaker and sentence. start/end/duration are seconds.
For exact assembly, use start_sample/end_sample and sample_rate. Start at
sample zero, place each WAV at start_sample, and fill gaps with digital
silence up to total_samples. End positions are exclusive. The expected
sample-count difference from the separately exported full.wav is zero.
逐句放到 start_sample 的位置，空隙补静音，总长度为 total_samples。
采样数为精确依据，结束位置不包含该采样，复原容差为零采样。

SRT and VTT use the same estimated speech boundaries as the existing export.
Cuts may remove spoken words; subtitle text is retained and needs review.
字幕沿用估计发声边界；剪切可能删去发音，字幕文字仍需人工核对。

This CSV/JSON describes audio placement. It is not a Premiere/Resolve project
file and does not promise automatic timeline import in editing applications.
这是素材与时间位置清单，不是剪辑软件工程，不承诺自动导入时间轴。

Generated by VoxStage. Package format: 1.
''',encoding='utf-8')
        archive = Path(temp)/'delivery.zip'
        with zipfile.ZipFile(archive,'w',compression=zipfile.ZIP_DEFLATED) as bundle:
            for path in sorted(staging.rglob('*')):
                if path.is_file():bundle.write(path,Path('delivery')/path.relative_to(staging))
        # Replace only this generated artifact after every file has been written.
        destination = output/'delivery'
        if destination.is_symlink():raise ValueError('交付目录不能是符号链接。')
        if destination.exists():shutil.rmtree(destination)
        staging.replace(destination)
        archive.replace(output/'delivery.zip')

# 最后更新：2026-09-11 · Astra
