import {useEffect,useRef,useState,type ReactNode} from 'react';
import {rememberDraft,forgetDraft,abandonDraft,silentLines,type DraftResume} from './draftResume';
import './review.css';
type Unit={id:string;text:string;kind:'narration'|'dialogue';speaker:string;blank?:boolean;suggested?:string;tier?:'suggested';basis?:string;hint?:string;edited?:boolean;certain?:boolean;typing?:boolean;stand_in?:boolean;block?:number;para?:number;source?:'tag'|'model'|'mark';silent?:boolean;cast_id?:string;decided?:{edited:boolean;confirmed:boolean;source:string}};
type Cast={id:string;name:string;aliases:string[];colours:string[];sex:string;source:string;introduced?:{draft_id?:string;unit_id?:string}|null;split_from?:string};
type Decision={speaker:string;kind:'narration'|'dialogue';cast_id?:string|null;edited:boolean;confirmed:boolean;source:string};
type Draft={draft_id:string;units:Unit[];notice?:string|null;revision?:number;language?:'zh'|'en';decisions?:Record<string,Decision>;cast?:Cast[];model?:{id:string|null;note:string};confirmed_project_id?:string|null};
type Props={resume?:DraftResume|null;onAbandoned?:(id:string)=>void;sourceForm?:ReactNode;sourceActions?:ReactNode;sourceInfo?:{text:string;name:string;language:'zh'|'en';onName:(name:string)=>void};request:(path:string,method?:string,data?:unknown)=>Promise<any>;onCreated:(project:any)=>Promise<void>;onClose:()=>void;limit?:number;seed?:{name:string;language:'zh'|'en';text:string;knownNames?:string[];book?:{id:string;index:number};hints?:{start:number;end:number;speaker:string}[];silent?:number[];cut?:'lines'}|null};
export function RoleImport({request,onCreated,onClose,onAbandoned,seed,resume,sourceForm,sourceActions,sourceInfo,limit=3000}:Props){
 const [text,setText]=useState(seed?.text??'');const [name,setName]=useState(seed?.name??'新的故事');const [language,setLanguage]=useState<'zh'|'en'>(seed?.language??'zh');
 const [draft,setDraft]=useState<Draft|null>(null);const [view,setView]=useState<'source'|'review'>('source');const [bulkTargets,setBulkTargets]=useState<Record<string,string>>({});const [castCursor,setCastCursor]=useState<Record<string,number>>({});const [flashId,setFlashId]=useState<string|null>(null);
 // 本人 2026-09-17: the cast table said a character had N lines but only led to the first; ◀ ▶ step through them.
 function showUnit(id:string){document.getElementById('role-unit-'+id)?.scrollIntoView({block:'center'});setFlashId(id);window.setTimeout(()=>setFlashId(x=>x===id?null:x),1600)}
 const chapter=seed?.book??resume?.book;
 const [pending,setPending]=useState<{old:string;speaker:string;ids:string[]}|null>(null);
 // Every decision the reviewer makes is saved with the draft as it is made,
 // in order, each save naming the revision it saw; the server refuses a
 // stale one with its current state and the page takes that state (Astra
 // 2026-09-16: 人工决定保存，刷新与重算保护). The draft can be resumed later.
 const revision=useRef(1);const queue=useRef<Promise<void>>(Promise.resolve());const [saving,setSaving]=useState(0);const [unsaved,setUnsaved]=useState(false);const [saveNote,setSaveNote]=useState('');
 const resumeKey=seed?(seed.book?`voxstage-draft-${seed.book.id}-${seed.book.index}`:`voxstage-draft-${seed.text.length}-${seed.text.slice(0,40)}`):'voxstage-draft-standalone';
 const [resumable,setResumable]=useState<{draft_id:string;revision:number}|null>(null);
 useEffect(()=>{try{const id=localStorage.getItem(resumeKey);if(id&&!draft)void request('/attribution/draft/'+id).then((g:{revision:number;confirmed_project_id?:string;abandoned?:boolean})=>{if(!g.confirmed_project_id&&!g.abandoned)setResumable({draft_id:id,revision:g.revision})}).catch(()=>{})}catch{}},[]);  // eslint-disable-line react-hooks/exhaustive-deps
 function takeDraft(d:Draft){const title=resume?.name??seed?.name??sourceInfo?.name??name;setName(title);rememberDraft({draft_id:d.draft_id,name:title,book:chapter,silent:seed?.silent??resume?.silent??silentLines(d.units)});setView('review');setText(d.units.map(u=>u.text).join(''));if(d.language)setLanguage(d.language);revision.current=d.revision??1;try{localStorage.setItem(resumeKey,d.draft_id)}catch{}setDraft({...d,units:d.units.map(u=>u.decided?{...u,edited:true}:u)})}
 useEffect(()=>{if(resume)void run(async()=>{const d=await request('/attribution/draft/'+resume.draft_id);if(d.confirmed_project_id){forgetDraft(resume.draft_id);throw new Error('这份草稿已经建成工程。')}takeDraft(d)})},[resume?.draft_id]);
 useEffect(()=>{if(draft)rememberDraft({draft_id:draft.draft_id,name,book:chapter,silent:seed?.silent??resume?.silent??silentLines(draft.units)})},[name,draft?.draft_id]);
 function applyServer(r:{revision:number;decisions?:Record<string,Decision>;cast?:Cast[];units?:Unit[]}){revision.current=r.revision;setDraft(d=>d&&({...d,revision:r.revision,decisions:r.decisions??d.decisions,cast:r.cast??d.cast,units:r.units?r.units.map(u=>{const mine=d.units.find(x=>x.id===u.id);return u.decided?{...u,edited:true}:(mine?{...mine,cast_id:u.cast_id,speaker:mine.edited?mine.speaker:u.speaker}:u)}):d.units}))}
 function save(patch:Record<string,unknown>){const d=latest.current;if(!d)return;setUnsaved(true);setSaving(n=>n+1);queue.current=queue.current.then(async()=>{try{const r=await request('/attribution/draft/'+d.draft_id,'PATCH',{expected_revision:revision.current,...patch});applyServer(r);setSaveNote('')}catch(e){const err=e as Error&{status?:number;detail?:{revision:number;decisions:Record<string,Decision>}};if(err.status===409&&err.detail){applyServer({revision:err.detail.revision,decisions:err.detail.decisions});try{const g=await request('/attribution/draft/'+d.draft_id);applyServer(g)}catch{}setSaveNote('这份草稿在别处改过了，页面已按最新状态更新；刚才这一步请再做一次。')}else setSaveNote('没保存上：'+err.message+'。可以继续改，稍后会再试。')}finally{setSaving(n=>n-1)}});void queue.current.then(()=>setUnsaved(false))}
 function decide(ids:string[],speaker:string|null,kind?:Unit['kind']){save({decisions:ids.map(id=>({unit_id:id,speaker,kind,edited:true,confirmed:true}))})}
 function carryAll(){const pd=pending;const d=latest.current;if(!pd||!d)return;const ids=d.units.filter(u=>pd.ids.includes(u.id)&&!u.edited&&!u.decided?.confirmed&&effective(u)===pd.old).map(u=>u.id);if(ids.length){setDraft(x=>x&&({...x,units:x.units.map(u=>ids.includes(u.id)?{...u,speaker:pd.speaker,edited:true}:u)}));decide(ids,pd.speaker)}setPending(null)}
 function offerBulk(c:Cast){const target=bulkTargets[c.id];if(!target)return;const d=latest.current;if(!d)return;const ids=d.units.filter(u=>u.kind==='dialogue'&&!u.blank&&!u.edited&&!u.decided?.confirmed&&effective(u)===c.name).map(u=>u.id);setPending({old:c.name,speaker:target,ids})}
 function renameCast(c:Cast,newName:string){const nn=newName.trim();if(!nn||nn===c.name)return;setDraft(d=>d&&({...d,units:d.units.map(u=>u.cast_id===c.id||(!u.cast_id&&u.speaker===c.name)?{...u,speaker:nn}:u),cast:d.cast?.map(x=>x.id===c.id?{...x,name:nn,aliases:[...x.aliases.filter(a=>a!==nn),c.name]}:x)}));save({rename:{cast_id:c.id,name:nn}})}
 // Review effort, recorded with the project: what the page showed when the draft arrived
 // and what the person changed, so the automation can be measured run by run.
 const started=useRef<{at:number;dialogue:number;orange:number;yellow:number;initial:Record<string,{tier:string;speaker:string}>}|null>(null);const [waiting,setWaiting]=useState(false);const [error,setError]=useState('');const [debugText,setDebugText]=useState('');const debugBox=useRef<HTMLTextAreaElement>(null);
 const unresolved=(s:string)=>!s.trim()||s.trim().toUpperCase()==='UNKNOWN';
 const names=[...new Set([...(seed?.knownNames??[]),...(draft?.units.filter(u=>u.kind==='dialogue').map(u=>u.speaker.trim()).filter(Boolean)??[])])].filter(n=>n.toUpperCase()!=='UNKNOWN'&&n.toUpperCase()!=='NARRATOR');
 // Two people taking turns: once the reviewer has named the last two distinct
 // speakers, an unresolved line is suggested as the one who did not speak last.
 // A suggestion only -- it is shown in the field, never adopted on its own.
 // Three tiers on the review page. A speaker the model named, or the person
 // typed: plain. A line the program filled itself — two people taking turns,
 // so the unresolved line goes to the one who did not speak last — yellow: it
 // stands unless changed, and confirming adopts it. A line nobody can place:
 // orange, and it must be chosen before the project is created.
 // Yellow comes from three places, in this order of trust: the model's own
 // judgement when it said the passage did not settle it, the way the character
 // talks in chapters a person confirmed (both filled by the server), and two
 // people taking turns (filled here). Anything the person types is plain.
 // Turn-taking stays inside one exchange (the server numbers them; a long
 // stretch of narration or a change of time or place starts a new one) and
 // anchors only on lines that are settled — by the person, the model with
 // certainty, a tag or a stand-in — never on another guess (Astra 2026-09-15).
 const turnTaking:Record<string,string>={};{let recent:string[]=[];let block:number|undefined;for(const u of draft?.units??[]){if(u.kind!=='dialogue'||u.blank)continue;if(u.block!==block){recent=[];block=u.block}if(!unresolved(u.speaker)){const anchor=u.edited||u.tier!=='suggested'||u.stand_in;if(anchor)recent=[u.speaker.trim(),...recent.filter(n=>n!==u.speaker.trim())].slice(0,2);continue}if(recent.length===2){const s=recent[1];turnTaking[u.id]=s;recent=[s,recent[0]]}}}
 const effective=(u:Unit)=>u.edited?(unresolved(u.speaker)?'':u.speaker.trim()):unresolved(u.speaker)?(turnTaking[u.id]??''):u.speaker.trim();
 const tier=(u:Unit)=>u.kind!=='dialogue'?'':u.edited?(unresolved(u.speaker)?'unknown':'named'):unresolved(u.speaker)?(turnTaking[u.id]?'suggested':'unknown'):(u.tier==='suggested'?'suggested':'named');
 const basis=(u:Unit)=>u.tier==='suggested'&&!u.edited&&!unresolved(u.speaker)?(u.basis??'程序填的'):turnTaking[u.id]&&unresolved(u.speaker)?'按一来一往填的'+(u.hint&&u.hint!==turnTaking[u.id]?`（说话习惯倒像 ${u.hint}）`:''):'';
 const unknownUnits=draft?.units.filter(u=>!u.blank&&tier(u)==='unknown')??[];const suggestedUnits=draft?.units.filter(u=>!u.blank&&tier(u)==='suggested')??[];const unknown=unknownUnits.length;const suggestedCount=suggestedUnits.length;
 const [reviewCursor,setReviewCursor]=useState<{unknown:number;suggested:number}>({unknown:0,suggested:0});
 function jumpReview(kind:'unknown'|'suggested',step=0){const list=kind==='unknown'?unknownUnits:suggestedUnits;if(!list.length)return;const current=Math.min(reviewCursor[kind],list.length-1);const next=step===0?current:(current+step+list.length)%list.length;setReviewCursor(c=>({...c,[kind]:next}));showUnit(list[next].id)}
 async function run(task:()=>Promise<void>){setWaiting(true);setError('');try{await task()}catch(e){setError((e as Error).message)}finally{setWaiting(false)}}
 useEffect(()=>{if(debugBox.current){debugBox.current.scrollTop=debugBox.current.scrollHeight}},[debugText]);
 async function createDraft(data:Record<string,unknown>){const debugId=crypto.randomUUID().replace(/-/g,'');setDebugText('[VoxStage] 正在启动本地模型…');const pull=async()=>{try{const r=await request('/attribution/debug/'+debugId);setDebugText(r.text||'[VoxStage] 暂无输出…')}catch{}};const timer=window.setInterval(()=>void pull(),600);try{return await request('/attribution/draft','POST',{...data,debug_id:debugId})}finally{window.clearInterval(timer);await pull()}}
 function change(id:string,values:Partial<Unit>){setDraft(d=>d&&({...d,units:d.units.map(u=>u.id===id?{...u,...values}:u)}))}
 // Learn as the reviewer works: once a name is settled by hand, every line still
 // yellow or orange is scored again against the settled ones (plus the book's
 // confirmed chapters) — the same habits that filled the first suggestions.
 const resuggest=useRef<ReturnType<typeof setTimeout>|null>(null);const latest=useRef<Draft|null>(null);latest.current=draft;
 function settle(id:string,speaker:string){

  change(id,{speaker:speaker||'UNKNOWN',edited:true});decide([id],speaker||'UNKNOWN');
  if(resuggest.current)clearTimeout(resuggest.current);
  resuggest.current=setTimeout(()=>{
   const d=latest.current;if(!d)return;
   const units=d.units.filter(u=>!u.blank&&u.kind==='dialogue').map(u=>({id:u.id,text:u.text,kind:u.kind,speaker:u.edited?u.speaker:(u.tier==='suggested'&&!u.stand_in?'':u.speaker),fixed:u.edited?!unresolved(u.speaker):(u.tier!=='suggested'&&!unresolved(u.speaker)),turn:(!u.edited&&unresolved(u.speaker)&&turnTaking[u.id])||'',source:u.edited?'person':(u.source==='tag'?'tag':(u.tier!=='suggested'&&!unresolved(u.speaker)?'model':'guess'))}));
   const asked=revision.current;request('/attribution/suggest','POST',{book_id:chapter?.id,units,draft_id:d.draft_id,revision:asked}).then((r:{suggestions:Record<string,{speaker:string;fill:boolean;basis?:string;hint?:string}>;revision?:number|null})=>{if(revision.current!==asked)return;
    setDraft(d2=>d2&&({...d2,units:d2.units.map(u=>{
     if(u.edited||u.kind!=='dialogue'||u.blank||u.stand_in)return u;   // a stand-in (众人/某人) stays until renamed by hand
     const sg=r.suggestions[u.id];if(!sg)return u;
     if(u.tier==='suggested'||unresolved(u.speaker)){
      if(sg.fill&&sg.basis!=='按一来一往填的')return {...u,speaker:sg.speaker,tier:'suggested' as const,basis:sg.basis??'按已确认的说话习惯，像是',hint:undefined};
      if(sg.basis==='按一来一往填的')return {...u,speaker:unresolved(u.speaker)?'UNKNOWN':u.speaker,hint:sg.hint};   // the page's own guess stands; habits only hint
      return {...u,speaker:unresolved(u.speaker)?'UNKNOWN':u.speaker,hint:sg.speaker};
     }
     return u;
    })}));
   }).catch(()=>{});
  },400);
 }
 // Arriving from the new-project form with unlabelled text: start straight away.
 useEffect(()=>{if(resume||!seed?.text.trim())return;setText(seed.text);setName(seed.name);setLanguage(seed.language);void run(async()=>{let id:string|null=null;try{id=localStorage.getItem(resumeKey)}catch{}if(id){try{const previous=await request('/attribution/draft/'+id);if(!previous.confirmed_project_id&&!previous.abandoned){setResumable({draft_id:id,revision:previous.revision});return}}catch(e){if((e as Error&{status?:number}).status!==400&&(e as Error&{status?:number}).status!==404)throw e}try{localStorage.removeItem(resumeKey)}catch{}}takeDraft(await createDraft({script:seed.text,language:seed.language,book_id:chapter?.id,hints:seed.hints,silent:seed.silent,cut:seed.cut}))})},[seed]);

 return <div className="overlay role-overlay"><section className={'dialog role-import'+(draft?' is-review':'')} role="dialog" aria-modal="true" aria-labelledby="role-import-title">
  <div className="dialog-title role-header"><h2 id="role-import-title">{draft?'角色复核':'新建工程'}</h2><label className="role-project-name">工程名称<input value={!draft&&sourceInfo&&!resume?sourceInfo.name:name} maxLength={120} disabled={waiting} onChange={e=>{setName(e.target.value);if(!draft)sourceInfo?.onName(e.target.value)}}/></label>{draft&&!draft.confirmed_project_id&&<button type="button" className="role-abandon" disabled={waiting||saving>0} title="放弃这份没做完的复核；原稿和已建好的工程不受影响" onClick={()=>{if(!confirm('放弃这份角色复核？\n\n草稿不再提示；原稿和已建好的工程都不受影响。'))return;void run(async()=>{await request('/attribution/draft/'+draft.draft_id,'DELETE');abandonDraft(draft.draft_id);onAbandoned?.(draft.draft_id);onClose()})}}>放弃草稿</button>}<button disabled={waiting||saving>0} aria-label="关闭角色草稿" onClick={onClose}>✕</button></div>
  <div className="role-nav"><div role="tablist" aria-label="原稿与角色复核"><button role="tab" id="source-tab" aria-selected={view==='source'} aria-controls="source-panel" onClick={()=>setView('source')}>原稿</button><button role="tab" id="review-tab" aria-selected={view==='review'} aria-controls="review-panel" disabled={!draft} onClick={()=>setView('review')}>角色复核</button></div><span className="role-count" title="按 Unicode 字符计，包含标点与空白">共 {Array.from(!draft&&sourceInfo&&!resume?sourceInfo.text:text).length.toLocaleString()} 字符</span><span className="role-help">{draft?'切换保留复核进度 · 修改自动保存':'本机分析 · 原文保留'}</span></div>
  {!draft&&resumable&&<div className="carry-bar" role="status"><span>上次的复核还没做完（第 {resumable.revision} 版，改动已保存）。</span><button type="button" className="primary" disabled={waiting} onClick={()=>void run(async()=>{takeDraft(await request('/attribution/draft/'+resumable.draft_id));setResumable(null)})}>继续上次的复核</button><button type="button" disabled={waiting} onClick={()=>{try{localStorage.removeItem(resumeKey)}catch{}setResumable(null)}}>重新开始</button></div>}
  <section id="source-panel" role="tabpanel" aria-labelledby="source-tab" className="role-source-panel" hidden={view!=='source'}>{sourceForm&&!draft&&!resume?<><fieldset className="import-workspace-fields" disabled={waiting}>{sourceForm}</fieldset><fieldset className="role-source-footer import-workspace-actions" disabled={waiting}>{waiting&&<span>正在本机分析…</span>}{sourceActions}</fieldset></>:<><label className="role-source-language">稿件语言<select value={language} disabled={waiting||!!draft} onChange={e=>setLanguage(e.target.value as 'zh'|'en')}><option value="zh">中文</option><option value="en">English</option></select></label>
   <label>未标注角色的原文<textarea aria-label="未标注角色的原文" rows={10} maxLength={limit} disabled={waiting} readOnly={!!draft} value={text} onChange={e=>setText(e.target.value)}/></label>
   <div className="role-source-footer"><span className="muted">{draft?'查看原稿不会重新分析；改字可在建立工程后进行。':`每次最多 ${limit} 字符 · 生成后请复核角色`}</span>{draft?<button onClick={()=>setView('review')}>返回角色复核</button>:
   <button className="primary" disabled={waiting||!text.trim()} onClick={()=>void run(async()=>takeDraft(await createDraft({script:text,language,book_id:chapter?.id,hints:seed?.text===text?seed?.hints:undefined,silent:seed?.text===text?seed?.silent:undefined,cut:seed?.text===text?seed?.cut:undefined})))}>{waiting?'正在本机分角色，请稍候…':'生成角色草稿'}</button>}</div>
  </>}{debugText&&<label className="role-debug">模型处理输出（临时）<textarea ref={debugBox} readOnly rows={10} wrap="soft" value={debugText}/><small>显示本地 llama-server 的实时输出，以及本次字符数、片段数、context、token 用量和模型返回内容。</small></label>} </section>{draft&&<section id="review-panel" role="tabpanel" aria-labelledby="review-tab" className="role-review-panel" hidden={view!=='review'}>{(()=>{if(!started.current){const ds=draft.units.filter(u=>!u.blank&&u.kind==='dialogue');started.current={at:Date.now(),dialogue:ds.length,orange:ds.filter(u=>tier(u)==='unknown').length,yellow:ds.filter(u=>tier(u)==='suggested').length,initial:Object.fromEntries(draft.units.map(u=>[u.id,{tier:tier(u),speaker:effective(u)}]))}}return null})()}<div className="role-summary" aria-label="复核概况"><span><strong>{draft.units.filter(u=>!u.blank&&u.kind==='dialogue').length}</strong> 句对白</span><span className={'review-nav-chip '+(unknown?'needs-choice':'')}><button type="button" aria-label="上一处待指定" disabled={!unknown} onClick={()=>jumpReview('unknown',-1)}>◀</button><button type="button" className="review-nav-main" disabled={!unknown} onClick={()=>jumpReview('unknown',0)}><strong>{unknown}</strong> 处待指定</button><button type="button" aria-label="下一处待指定" disabled={!unknown} onClick={()=>jumpReview('unknown',1)}>▶</button></span><span className={'review-nav-chip needs-review'+(!suggestedCount?' is-empty':'')}><button type="button" aria-label="上一处建议复核" disabled={!suggestedCount} onClick={()=>jumpReview('suggested',-1)}>◀</button><button type="button" className="review-nav-main" disabled={!suggestedCount} onClick={()=>jumpReview('suggested',0)}><strong>{suggestedCount}</strong> 处建议复核</button><button type="button" aria-label="下一处建议复核" disabled={!suggestedCount} onClick={()=>jumpReview('suggested',1)}>▶</button></span><span className="role-summary-note" title={draft.model?.note}>已填入的角色也请核对{draft.model?.note&&` · ${draft.model.note}`}</span></div>{draft.notice&&<p role="alert" className="line-error">{draft.notice}</p>}<div className="role-review-layout"><aside className="role-cast-panel" aria-label="人物与称呼"><div className="role-panel-heading"><strong>人物与称呼</strong><span>{draft.cast?.length??names.length} 位</span></div><p className="role-panel-help">改名统一称呼；批量更改只影响本稿未确认片段。</p>
   {draft.cast&&draft.cast.length>0&&<section className="cast-table" aria-label="人物表"><div className="cast-head"><strong>人物表</strong><small>名字可以改，改了这个人的句子都跟着改；别名是原文里的其他称呼。</small><span className={'save-state '+(saving||unsaved?'busy':'')}>{saving||unsaved?'保存中…':saveNote?'保存需处理':'已保存'}</span></div>
    <table><thead><tr><th>名字</th><th>别名</th><th>出处</th><th>来源</th>{draft.cast.some(c=>c.colours.length)&&<th>颜色</th>}<th>批量更改归属</th></tr></thead><tbody>{draft.cast.map(c=>{const spoken=draft.units.filter(u=>!u.blank);const mine=spoken.map((u,n)=>({u,n})).filter(({u})=>u.kind==='dialogue'&&(u.cast_id===c.id||u.speaker===c.name));const pos=Math.min(castCursor[c.id]??0,Math.max(0,mine.length-1));const step=(d:number)=>{const next=(pos+d+mine.length)%mine.length;setCastCursor(x=>({...x,[c.id]:next}));showUnit(mine[next].u.id)};return <tr key={c.id}><td><input aria-label={'人物 '+c.name+' 的名字'} defaultValue={c.name} maxLength={80} disabled={waiting} onBlur={e=>renameCast(c,e.target.value)} onKeyDown={e=>{if(e.key==='Enter')(e.target as HTMLInputElement).blur()}}/></td><td>{c.aliases.join('、')||'—'}</td><td className="cast-where">{mine.length>0?<span className="cast-nav">{mine.length>1&&<button type="button" aria-label={c.name+' 的上一句'} title="上一句" disabled={waiting} onClick={()=>step(-1)}>◀</button>}<button type="button" className="cast-source-link" title="跳到这一句" onClick={()=>showUnit(mine[pos].u.id)}>片段 {mine[pos].n+1} ↗</button>{mine.length>1&&<button type="button" aria-label={c.name+' 的下一句'} title="下一句" disabled={waiting} onClick={()=>step(1)}>▶</button>}<small>{mine.length>1?`第 ${pos+1}/${mine.length} 句`:'1 句'}</small></span>:(c.introduced?.unit_id?'本书前面的章节':'—')}</td><td>{({person:'你定的',mark:'原稿里标的',tag:'叙述点名',model:'模型',rule:'程序推断',alias:'别名',template:'模板'} as Record<string,string>)[c.source]??c.source}</td>{draft.cast!.some(x=>x.colours.length)&&<td>{c.colours.map(col=><span key={col} className="colour-chip" style={{background:col==='none'?'#000':col}} title={col}/>)}</td>}<td className="cast-bulk"><select aria-label={c.name+' 批量更改为'} value={bulkTargets[c.id]??''} disabled={waiting||saving>0} onChange={e=>setBulkTargets(x=>({...x,[c.id]:e.target.value}))}><option value="">改归属为…</option>{names.filter(n=>n!==c.name).map(n=><option key={n} value={n}>{n}</option>)}</select><button disabled={waiting||saving>0||!bulkTargets[c.id]} onClick={()=>offerBulk(c)}>批量更改</button></td></tr>})}</tbody></table>
    {saveNote&&<p role="alert" className="line-error">{saveNote}</p>}</section>}
   <p className="role-panel-help role-panel-footnote">别名记录同一人物的不同称呼；同姓或称呼相近，不一定是同一个人。</p></aside><div className="role-units" tabIndex={0} aria-label="原文与逐句角色">{draft.units.filter(u=>!u.blank).map((u,i,list)=><article className={'role-unit '+(tier(u)==='unknown'?'role-unknown':tier(u)==='suggested'?'role-suggested':'')+(pending?.ids.includes(u.id)?' role-carry':'')+(i>0&&list[i-1].para===u.para?' same-para':' para-first')+(flashId===u.id?' role-flash':'')} key={u.id} id={'role-unit-'+u.id}>
    <p><small>片段 {i+1}{(u.edited||u.decided?.confirmed)&&<span className="unit-tag confirmed">已确认</span>}{!u.edited&&!u.decided?.confirmed&&u.source==='tag'&&<span className="unit-tag">叙述提示</span>}{u.silent&&<span className="unit-tag">不朗读（标题）</span>}{u.source==='mark'&&<span className="unit-tag">原稿里标的</span>}</small><br/>{u.text.trim()}</p><div className="role-fields"><label>类型<select aria-label={`片段 ${i+1} 类型`} disabled={waiting} value={u.kind} onChange={e=>{const kind=e.target.value as Unit['kind'];const sp=kind==='narration'?'NARRATOR':u.speaker==='NARRATOR'?'UNKNOWN':u.speaker;change(u.id,{kind,speaker:sp,edited:true});decide([u.id],kind==='dialogue'?sp:null,kind)}}><option value="narration">旁白</option><option value="dialogue">对白</option></select></label>
    {u.kind==='dialogue'?<div className="speaker-review-field"><label>说话人{tier(u)==='suggested'&&<small>{basis(u)}，请结合原文确认</small>}{tier(u)==='unknown'&&<small>{u.hint?`像是 ${u.hint}，但把握不大——请选一个人物`:u.suggested?`模型写的是 ${u.suggested}，原文里没有这个名字——请选一个人物`:'待指定，请选一个人物'}</small>}
     {u.typing?<input autoFocus aria-label={`片段 ${i+1} 新人名`} disabled={waiting} placeholder="输入新人名，回车确定" maxLength={80} onKeyDown={e=>{if(e.key==='Enter'){const v=(e.target as HTMLInputElement).value.trim();change(u.id,{typing:false});if(v)settle(u.id,v)}if(e.key==='Escape')change(u.id,{typing:false})}} onBlur={e=>{const v=e.target.value.trim();change(u.id,{typing:false});if(v)settle(u.id,v)}}/>
     :<select aria-label={`片段 ${i+1} 说话人`} disabled={waiting} value={effective(u)} onChange={e=>{if(e.target.value==='__new__')change(u.id,{typing:true});else settle(u.id,e.target.value)}}><option value="">— 待指定 —</option>{[...new Set([...names,effective(u)].filter(Boolean))].map(n=><option key={n} value={n}>{n}</option>)}<option value="__new__">＋ 新人名…</option></select>}</label>{tier(u)==='suggested'&&<button type="button" className="confirm-suggestion" disabled={waiting||saving>0||!effective(u)} onClick={()=>settle(u.id,effective(u))}>✓ 确认建议</button>}</div>:<span>旁白</span>}</div>
   </article>)}</div></div>
   {pending&&<div className="carry-bar" role="status"><span>本稿 {pending.ids.length} 处未确认的「{pending.old}」→「{pending.speaker}」。已确认片段保留，不合并人物或别名。</span><button type="button" className="primary" disabled={waiting||saving>0||!pending.ids.length} onClick={carryAll}>确认更改</button><button type="button" onClick={()=>setPending(null)}>取消</button></div>}
   <div className="buttons role-review-actions"><span>{unknown?`还有 ${unknown} 处需要指定说话人`:'完成核对后，再建立工程'}</span><button disabled={waiting} onClick={()=>setView('source')}>查看原稿</button><button className="primary" disabled={waiting||unknown>0||saving>0||!!saveNote} onClick={()=>void run(async()=>{await queue.current;const st=started.current;const changed=draft.units.filter(u=>!u.blank&&st&&st.initial[u.id]&&(st.initial[u.id].speaker!==(u.kind==='dialogue'?effective(u):u.speaker)||(st.initial[u.id].tier===''?'narration':'dialogue')!==u.kind));const review=st?{seconds:Math.round((Date.now()-st.at)/1000),dialogue:st.dialogue,orange:st.orange,yellow:st.yellow,changed:changed.length,named_changed:changed.filter(u=>st.initial[u.id].tier==='named').length,yellow_changed:changed.filter(u=>st.initial[u.id].tier==='suggested').length,orange_filled:changed.filter(u=>st.initial[u.id].tier==='unknown').length}:undefined;const project=await request('/attribution/confirm','POST',{name,draft_id:draft.draft_id,labels:draft.units.map(u=>({id:u.id,kind:u.kind,speaker:u.kind==='dialogue'?(effective(u)||'UNKNOWN'):u.speaker})),book_id:chapter?.id,chapter_index:chapter?.index,review,silent:seed?.text===text?seed?.silent:(resume?.silent??silentLines(draft.units)),expected_revision:revision.current});try{localStorage.removeItem(resumeKey);forgetDraft(draft.draft_id)}catch{}await onCreated({...project,review})})}>{waiting?'正在保存…':'完成复核，建立工程'}</button></div>
  </section>}{error&&<p role="alert" className="line-error">{error}</p>}
 </section></div>
}
// 最后更新：2026-09-10 · Astra
